name: Generate codecov

on:
  workflow_call:
    inputs:
      package:
        description: 'Package to collect coverage for.'
        type: string
        required: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Zcodegen-backend=llvm
  RUSTC_WRAPPER: sccache

jobs:
  generate-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup CI environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-prefix: ${{ inputs.package }}

      - name: Collect coverage data
        run: >
          nix develop --command bash -c
          "cargo llvm-cov nextest --manifest-path=./workspace/Cargo.toml
          -p ${{ inputs.package }} --lcov --output-path report.lcov"

      - name: Upload to coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          flag-name: ${{ inputs.package }}
