name: Generate codecov

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  SCCACHE_GHA_ENABLED: true
  RUSTFLAGS: -Zcodegen-backend=llvm

jobs:
  generate-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup CI environment
        uses: cubething-qproj/infra/.github/actions/setup@main
        with:
          cargo-cache-prefix: coverage

      - uses: nicknovitski/nix-develop@v1

      - name: Detect package name
        id: pkg
        run: echo "name=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name')" >> "$GITHUB_OUTPUT"

      - name: Collect coverage data
        run: >
          cargo llvm-cov nextest --manifest-path=./workspace/Cargo.toml
          -p ${{ steps.pkg.outputs.name }} --lcov --output-path report.lcov

      - name: Upload to coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          flag-name: ${{ steps.pkg.outputs.name }}
